name: Deploy python package

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]

jobs:
  deploy-pypi-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'main' ||
       startsWith(github.event.workflow_run.head_branch, 'v'))
    steps:
      - name: Download t2iapi wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: dist/
      - name: Download t2iapi test results artifact
        uses: actions/download-artifact@v4
        with:
          name: html_unit_test
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: unittest_results/
      - name: Download pip freeze
        uses: actions/download-artifact@v4
        with:
          name: freeze
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: freeze/
      - name: Publish t2iapi to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Attach artifacts to github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.event.workflow_run.head_branch, 'v')
        with:
          files: |
            dist/*.whl
            freeze/pip_freeze.txt
            unittest_results/*.html
          prerelease: ${{ !startsWith(github.event.workflow_run.head_branch, 'v') }}