name: Integration tests

on:
  pull_request:
  push:

env:
  RELEASE_VERSION: 0

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Source dependency versions
        working-directory: config
        run: cat versions.txt >> $GITHUB_ENV

      - name: Install Protoc
        run: |
          sudo apt-get update && sudo apt-get install -y apt-utils unzip
          mkdir ${{ runner.temp }}/protoc_install
          wget https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.COMMON_PROTOC_VERSION }}/protoc-${{ env.COMMON_PROTOC_VERSION }}-linux-x86_64.zip \
            -P ${{ runner.temp }}/protoc_install
          unzip ${{ runner.temp }}/protoc_install/*.zip -d ${{ runner.temp }}/protoc_install/protoc
          echo "${{ runner.temp }}/protoc_install/protoc/bin" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Build t2iapi JAR
        working-directory: java
        run: ./gradlew jar

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build and install Python package
        working-directory: python
        run: |
          ./build_protobuf.sh
          python setup.py bdist_wheel
          pip install dist/t2iapi*.whl

      - name: Run integration tests
        working-directory: tests/java
        run: ./gradlew test -Dpython.executable=python

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: tests/java/build/reports/tests/test/**/*.*
          if-no-files-found: ignore
